name: qe-mini-example
channels:
  - default
  - conda-forge
dependencies:
  - python=3.7.*
  - sphinx=2.4.4
  - pip
  - pandas
  - matplotlib
  - seaborn
  - pymc3
  - scipy
  - graphviz
  - python-graphviz
  - pip:
    - quantecon
    - jupyter-book>=0.7.0b
    - arviz
