#######################################################################################
# Book settings
title : Introduction to Statistical Computing for Aspiring Data Scientists
author: Srijith Rajamohan, Ph.D.
logo: 'qe-logo-large.png'

# Information about where the book exists on the web
description: >-
  An introduction to Bayesian Statistics for computational statistics applications using PyMC3

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         :
    https://github.com/sjster/statistical_computing_book
  path_to_book                : "mini_book"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"
  
launch_buttons:
  colab_url: "https://colab.research.google.com"
  binderhub_url               : "https://mybinder.org"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
