#######################################################################################
# Book settings
title : Introduction to Computational Statistics with PyMC3
author: Srijith Rajamohan, Ph.D.
logo: 'logo_large.png' 

# Information about where the book exists on the web
description: >-
  An introduction to Bayesian Statistics for computational statistics applications using PyMC3

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         :
    https://github.com/sjster/statistical_computing_book
  path_to_book                : "mini_book"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"
  
launch_buttons:
  colab_url                   : "https://colab.research.google.com"
  binderhub_url               : "https://mybinder.org"
  thebe                       : true 

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
