#######################################################################################
# Book settings
title : Scientific Python QuickStart
author: Thomas J. Sargent and John Stachurski
logo: 'qe-logo-large.png'

# Information about where the book exists on the web
description: >-
  A brief introduction to Python programming for scientific applications.

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         :
    https://github.com/sjster/statistical_computing_executable
  path_to_book                : "notes"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"
  
launch_buttons:
  colab_url: "https://colab.research.google.com"
  binderhub_url               : "https://mybinder.org"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
