on:
  push:
    branches: 
     - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
  
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
