on:
  push:
    branches: 
     - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
      with:
          persist-credentials: false

    # Install dependencies
    - name: Set up Python 3.7
      uses: conda-incubator/setup-miniconda@v1 
      with:
          activate-environment: condaenv
          environment-file: environment.yml
          auto-update-conda: true
          python-version: 3.7
          auto-activate-base: false
  
    - shell: bash -l {0}
        run: |
          conda env update -n condaenv --file environment.yml
          conda info
          conda list

    # Build the book
    - name: Build the book
      run: |
          jupyter-book build mini_book/

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: mini_book/build/html # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch   
